### ISSUE TITLE
grub: duplicated menu items regarding the main OS

### ISSUE THREAD

**Issue by butangmucat** [AOSC-Dev/aosc-os-abbs#85] opened 2015-09-14 02:06 UTC
See the picture for what I am talking about. This is an old issue.
```
[[] AOSC OS3 (正在运行) - Orz VM VirtualBox                                     ]
                             GNU GRUB 2.02~beta2 版

┌──────────────────────────────────────────────────────────────────────────────┐
│*AOSC OS                                                                      │
│ Advanced options for AOSC OS                                                 │
│ AOSC OS (3.0.4) (on /dev/sda3)                                               │ *DUPLICATE!*
│ Advanced options for AOSC OS (3.0.4) (on /dev/sda3)                          │ *DUPLICATE!*
└──────────────────────────────────────────────────────────────────────────────┘

        Use the ↑ and ↓ keys to select which entry is highlighted,
        Press Enter to boot the selected OS, `e' to edit the commands
        before booting or `c' for a command-line.
```

**Comment by Arthur2e5** [comment] 2015-09-14 02:15
Used alternative text to save bandwidth.

**Comment by butangmucat** [comment] 2015-09-14 02:18
@Arthur2e5 Just curious, which data plan are you on?

**Comment by MingcongBai** [comment] 2015-09-14 02:19
> Just curious, which data plan are you on?

Can you try using another place for tea chatting?

**Comment by butangmucat** [comment] 2015-09-14 02:20
@MingcongBai I asked because I see no point why he is doing this.

**Comment by MingcongBai** [comment] 2015-09-14 02:21
> I asked because I see no point why he is doing this.

That was a word "used". I will delete the comments shortly.

**Comment by butangmucat** [comment] 2015-09-14 02:23
@MingcongBai no problem. But I do think that what @Arthur2e5 is not necessary.

**Comment by Arthur2e5** [comment] 2015-09-14 02:24
It took me five seconds to load your wallpaper.

**Comment by MingcongBai** [comment] 2015-09-14 02:26
It is possible to find that the first half is on `10_linux`'s part, and the dups are from `30_os-prober`, all in `/etc/grub.d`. I am trying to see a way to fix this.

**Comment by Arthur2e5** [comment] 2015-09-14 02:36
This Unicode Art graph is an excellent test of box-drawing glyphs, and may expose some problems in certain CJK 'monospace' families.

**Comment by MingcongBai** [comment] 2015-09-19 05:54
This issue is confirmed to be caused by running `grub-mkconfig` in chroot. This incident should be documented, however not a bug by design. Closing.

**Closed by MingcongBai** 2015-09-19 05:54 UTC
Labels: Bug, Investigating
