### ISSUE TITLE
LMMS: Whether some features should be enabled/disabled

### ISSUE THREAD

**Issue by liushuyu** [AOSC-Dev/aosc-os-abbs#149] opened 2016-02-20 06:05 UTC
As it was mentioned in our discussion before, LMMS experienced a kind of refactor, so many things changed and some configurations need to be changed. However, this will also **bring some cost**
- Qt4 or Qt5?
    LMMS can be compiled with either Qt4 or Qt5, but its Qt5 support isn't good, however, HiDPI display seems to have better support on Qt5

- Wine VST connect plugin?
   VST plugins are mostly Windows platform specified, so LMMS uses Wine to connect to them. The drawback here is that **this feature is experimental and can cause many troubles**.

- Python based Carla support?
   Carla is another audio plugin host. It's written in Python 3, and it is noticed to have some compilation difficulties...

So guys, what do you think?

**Comment by MingcongBai** [comment] 2016-02-20 06:07
Honestly just enable them all...

Modules can be listed as `$PKGRECOM` if it really looks too much for a list. As of hard-to-build stuff, just throw it at me.

I would not recommend Qt 5 if it's hella broken though.

**Comment by liushuyu** [comment] 2016-02-20 07:16
>I would not recommend Qt 5 if it's hella broken though.

Actually it can be compiled successfully, it just that the GUI looks ugly.

**Comment by MingcongBai** [comment] 2016-02-20 14:22
> Actually it can be compiled successfully, it just that the GUI looks ugly.

I though you said that VST plugin would not work when making a Qt 5 build?

**Comment by liushuyu** [comment] 2016-02-20 14:44
I suppose that workarounds are also available when dealing with this scenario
BTW, if you don't have the relevant packages installed, it will skip the related target, but no emit an error

**Comment by MingcongBai** [comment] 2016-02-20 14:46
> BTW, if you don't have the relevant packages installed, it will skip the related target, but no emit an error 

See, that's what I told you before...

> Modules can be listed as $PKGRECOM if it really looks too much for a list. As of hard-to-build stuff, just throw it at me.

**Comment by liushuyu** [comment] 2016-02-20 14:47
I am currently still making a list of missing dependencies (too many!) ... So I believe my HDD will fail very soon (ccache also enabled!) ... XD

**Comment by MingcongBai** [comment] 2016-02-20 14:48
> I am currently still making a list of missing dependencies (too many!) ... So I believe my HDD will fail very soon (ccache also enabled!) ... XD

Well good luck then. Thanks for doing this.

**Comment by liushuyu** [comment] 2016-02-20 15:25
Okay, now we can come to a conclusion that:
- Use Qt5 if possible
- Enable all features and make them selectable to end users

Correct?

**Comment by MingcongBai** [comment] 2016-02-20 15:26
Not quite sure with the Qt 5 part yet. Could you tell me what those "workarounds" are?

**Comment by liushuyu** [comment] 2016-02-20 15:31
>Not quite sure with the Qt 5 part yet. Could you tell me what those "workarounds" are?

Quite simple, just force enable it and see what will happen next...
Or build Carla with Qt4 and use its VST support instead of LMMS's support
But I have never successfully built Carla yet :-(
It always output with 'undefined reference to ', but I really had all required libraries installed

**Comment by liushuyu** [comment] 2016-02-20 15:31
>Not quite sure with the Qt 5 part yet. Could you tell me what those "workarounds" are?

Quite simple, just force enable it and see what will happen next...
Or build Carla with Qt4 and use its VST support instead of LMMS's support
But I have never successfully built Carla yet :-(
It always output with 'undefined reference to ', but I really had all required libraries installed

**Comment by MingcongBai** [comment] 2016-02-20 15:33
Well. If something "went wrong" I would suggest that we stick with Qt 4 for now. As of failed packages, hit me up in the channel so I can get them sorted out.

**Comment by liushuyu** [comment] 2016-02-20 15:49
Well then
What about build type? 
They currently have :
- Standard release 
- Minimum size release 
- Debuggable release 
- Debug build (Anyway, we can't use this one)

**Comment by liushuyu** [comment] 2016-02-22 01:55
[Progress update] 5 dependencies packaged...

**Comment by LionNatsu** [comment] 2016-02-23 14:48
I would rather die if it'a audio workstation without VST support. (However I am not a LMMS user yet.)

**Comment by MingcongBai** [comment] 2016-02-23 15:58
> I would rather die if it'a audio workstation without VST support. (However I am not a LMMS user yet.)

The main issue here is that it's a module that relies on Wine... While it's all fine and well to provide it as a modules and set `wine` as one of its `PKGRECOM`, it may be unpredictable that when it will stop working due to a random regression or bug (well the moral suggests that we report it in the first place, but it is still a feasible source of annoyance).

**Comment by liushuyu** [comment] 2016-02-24 02:53
>but it is still a feasible source of annoyance).

Yes. And image the two apps full of black magic, which will cooperate together... It will be annoying to think what if either of they crashed. 

And this function doesn't provide the support for VST 3 plugins under Linux due to some limitations. So if you want to use them, I am sorry to tell you that currently this is not possible.

Anyway, I will try to provide the module but you will take the risk to use it.

**Comment by MingcongBai** [comment] 2016-02-24 03:03
> And image the two apps full of black magic, which will cooperate together... 

Sounds un-scientific to me, but well you are right to a certain extent.

> Anyway, I will try to provide the module but you will take the risk to use it.

On that account, i fully agree with you.

**Comment by MingcongBai** [comment] 2016-02-28 00:55
Marking as done.

**Closed by MingcongBai** 2016-02-28 00:55 UTC
Labels: discussion-needed, Upgrade
