### ISSUE TITLE
icu: Replace ICU source/layout/ with icu-le-hb

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-abbs#119] opened 2015-11-23 04:26 UTC
At least the ICU guys said that the Layout Engine part is deprecated and people should use HarfBuzz: http://userguide.icu-project.org/layoutengine

And HarfBuzz guys point us to a C ABI-compatible, C++ API-compatible layer called icu-le-hb: https://github.com/behdad/icu-le-hb

**Comment by MingcongBai** [comment] 2015-11-23 04:30
> And HarfBuzz guys point us to a C ABI-compatible, C++ API-compatible layer called icu-le-hb: https://github.com/behdad/icu-le-hb

As in a dependency to `harfbuzz` itself?

**Comment by Arthur2e5** [comment] 2015-11-23 04:31
@MingcongBai It's basically a implementation of that engine's API using HarfBuzz.

**Comment by MingcongBai** [comment] 2015-11-23 04:31
> @MingcongBai It's basically a implementation of that engine's API using HarfBuzz.

Okay...

**Comment by MingcongBai** [comment] 2015-11-23 04:32
Shall we wait for the next upstream release? I don't see a point of changing this immediately.

**Comment by Arthur2e5** [comment] 2015-11-23 04:32
Sure.

**Comment by Arthur2e5** [comment] 2015-11-23 04:33
Oh, wait, it's simply, uh, stable, so… use git HEAD

**Comment by Arthur2e5** [comment] 2015-11-23 04:33
(Look at that code……Really trivial really simple

**Comment by MingcongBai** [comment] 2015-11-23 04:33
> Oh, wait, it's simply, uh, stable, so… use git HEAD

Now you are making me concerned over this change... I did not realize that.

**Comment by Arthur2e5** [comment] 2015-11-23 04:34
Last update 3 months ago. Much better than ICU LE…

**Comment by MingcongBai** [comment] 2015-11-23 04:34
> Last update 3 months ago. Much better than ICU LE…

Do you think they will merge this project some time in the future?

**Comment by Arthur2e5** [comment] 2015-11-23 04:35
I don't think so. But given its terribly high compatibility including source code layout similarities, we can even patch ICU to use this layer instead of its deprecated LE.

**Comment by MingcongBai** [comment] 2015-11-23 04:36
> I don't think so. But given its terribly high compatibility including source code layout similarities, we can even patch ICU to use this layer instead of its deprecated LE.

Very interesting indeed. Still, wait for the next `harfbuzz` point-point release, and we can raise this issue again.

Thanks for sharing.

**Comment by Arthur2e5** [comment] 2016-04-23 16:06
http://userguide.icu-project.org/layoutengine/paragraph shows a very complicated building procedure mainly caused by the fact that the LE is out of the library. Paragraphs depends on LE, and LE depends on the rest of ICU, so they are building "rest of ICU" first, then the LE shim, and finally the Paragraph.

Patching ICU won't cause that much BS, since `configure` knows everything already.

**Comment by MingcongBai** [comment] 2016-04-23 22:43
It's actually pretty convenient...

**Comment by Arthur2e5** [comment] 2016-04-23 22:46
Comparing icu-le-hb/src with icu-57.1/source/layout.

**Comment by MingcongBai** [comment] 2016-05-03 00:48
Right, let's do this when I would find time to do the 57.1 bump...

**Comment by MingcongBai** [comment] 2016-11-17 17:23
Are we still going to do this? @Artoria2e5

**Comment by Artoria2e5** [comment] 2016-11-17 17:35
Yes.

**Comment by Artoria2e5** [comment] 2019-10-21 12:57
Meow?

**Comment by MingcongBai** [comment] 2021-03-15 02:27
Stalled (feature/design change) issue, closing. Please open a new issue if this thought arises again.

**Closed by MingcongBai** 2021-03-15 02:27 UTC
Labels: abi-break, enhancement, investigating

**Comment by Artoria2e5** [comment] 2021-03-19 06:38
icu58 has no layout engine at all, so I guess it's really just fixed.

**Comment by MingcongBai** [comment] 2021-03-19 06:42
Sounds good.
