### ISSUE TITLE
kdeconnect: cannot send file to mobile phone

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#668] opened 2017-06-25 17:10 UTC
When I tried to send some file by the right-click menu...

```
(journalctl --user)
kdeconnectd[3827]: kdeconnect.core: Error opening a port in range 1739-1764 for file transfer
```

Reproducible here by command line.
```
kdeconnect-cli -d 861155f8ce????? --share /home/lion/atextfile
```

Version: kdeconnect/os-amd64,now 1.0.2

No firewall, nothing was sitting on these ports.

**Comment by LionNatsu** [comment] 2017-06-27 11:05
I can't reproduce now, yes, without restarting the computer. Very strange.
The code, where reported this error message, may be helpful for debugging.

**Comment by MingcongBai** [comment] 2017-06-27 13:25
Could it be related to LAN settings? I have heard that from @LER0ever .

**Comment by LionNatsu** [comment] 2017-06-27 14:09
No idea. But I did change QoS setting on router.

**Comment by liushuyu** [comment] 2019-01-28 22:13
Marking as resolved since unable to reproduce

**Closed** 2019-01-29 21:16 UTC
Labels: Ready, bug, investigating
