### ISSUE TITLE
virtualbox: Failed to create virtual machine

### ISSUE THREAD

**Issue by eatradish** [AOSC-Dev/aosc-os-abbs#1619] opened 2019-01-27 13:03 UTC
Bug description
-----------------------

Create any virtual machine with the error "Could not launch a process for the machine 'test' (VERR_FILE_NOT_FOUND)"

Reproducing steps
---------------------------

1. open virtualbox
2. create new vm
3. open this vm

Update channel(s)
--------------------------
Explosive

Package and version
------------------------------

```
➜  ~ dpkg -s virtualbox
Package: virtualbox
Status: install ok installed
Section: emulation
Installed-Size: 486420
Maintainer: sakiiily <sakiiily@aosc.io>
Architecture: amd64
Version: 6.0.2-1
Depends: acpica-unix (>= 20180629), cdrkit (>= 1:1.1.11-1), libidl2 (>= 0.8.14-2), openssl (>= 1.0.2q), curl (>= 7.62.0), gcc (>= 7.3.1-1), libpng (>= 1.6.35-1), python-2 (>= 2.7.15-2), sdl-ttf (>= 2.0.11-4), libvpx (>= 1.7.0-1), libxml2 (>= 2.9.8-3), procps (>= 3.3.15), shared-mime-info (>= 1.10), zlib (>= 1.2.11), qt-5 (>= 1:5.11.3+wk5.212.0), vde2 (>= 1:2.3.2), net-tools (>= 20160828), dkms (>= 1:2.6.1), make (>= 4.2.1), linux-pam (>= 1.3.1), xorg-server (>= 1.20.3-1), x11-app (>= 7.7.20180328)
Description: Full-featured virtualization software suite from Oracle
➜  ~ uname -a
Linux eat-x220i 4.19.9-aosc-main #1 SMP PREEMPT Sun Dec 16 16:00:32 CST 2018 x86_64 GNU/Linux

```

**Comment by cthbleachbit** [comment] 2019-01-27 16:30
Cannot reproduce on same version of vbox...

**Comment by cthbleachbit** [comment] 2019-01-27 16:57
Seems like virtualbox is having issues with its own graphical interface as starting with the following command works.

```
VBoxManage startvm ${VM_NAME_HERE} --type sdl
VBoxManage startvm ${VM_NAME_HERE} --type headless
```

**Comment by cthbleachbit** [comment] 2019-01-27 17:02
Running strace of `VBoxManage startvm ${VM_NAME_HERE} --type gui` reveals following missing files:

```
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/gconv/gconv-modules.cache", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("/etc/vbox/module_not_compiled", 0x7ffcc91b8f10) = -1 ENOENT (No such file or directory)
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/tls/x86_64/x86_64/VBoxDDU.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/virtualbox/tls/x86_64/x86_64", 0x7ffc98fb4800) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/tls/x86_64/VBoxDDU.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/virtualbox/tls/x86_64", 0x7ffc98fb4800) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/tls/x86_64/VBoxDDU.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/virtualbox/tls/x86_64", 0x7ffc98fb4800) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/tls/VBoxDDU.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/virtualbox/tls", 0x7ffc98fb4800) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/x86_64/x86_64/VBoxDDU.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/virtualbox/x86_64/x86_64", 0x7ffc98fb4800) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/x86_64/VBoxDDU.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/virtualbox/x86_64", 0x7ffc98fb4800) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/x86_64/VBoxDDU.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/virtualbox/x86_64", 0x7ffc98fb4800) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libcrypt.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libcrypt.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/librt.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/librt.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libdl.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libdl.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libxml2.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libxml2.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libcurl.so.4", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libcurl.so.4", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libssl.so.1.0.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libssl.so.1.0.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libcrypto.so.1.0.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libcrypto.so.1.0.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libm.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libm.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/liblzma.so.5", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/liblzma.so.5", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libnghttp2.so.14", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libnghttp2.so.14", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libidn2.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libidn2.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/librtmp.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/librtmp.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libgssapi_krb5.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libgssapi_krb5.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libkrb5.so.3", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libkrb5.so.3", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libk5crypto.so.3", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libk5crypto.so.3", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libcom_err.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libcom_err.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libbrotlidec.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libbrotlidec.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/tls/x86_64/x86_64/libunistring.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/tls/x86_64/x86_64", 0x7ffc98fb3e00) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/tls/x86_64/libunistring.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/tls/x86_64", 0x7ffc98fb3e00) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/tls/x86_64/libunistring.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/tls/x86_64", 0x7ffc98fb3e00) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/tls/libunistring.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64/x86_64/libunistring.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/x86_64/x86_64", 0x7ffc98fb3e00) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64/libunistring.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/x86_64", 0x7ffc98fb3e00) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64/libunistring.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/x86_64", 0x7ffc98fb3e00) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libkrb5support.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libkrb5support.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libkeyutils.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libkeyutils.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libresolv.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libbrotlicommon.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libbrotlicommon.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/gconv/gconv-modules.cache", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("/home/cth451/.VirtualBox", 0x7ffc98faeea0) = -1 ENOENT (No such file or directory)
access("/usr/lib/virtualbox/.autoreg", F_OK) = -1 ENOENT (No such file or directory)
access("/usr/lib/virtualbox/plugins", F_OK) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libnss_files.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libpng16.so.16", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libpng16.so.16", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libvpx.so.5", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libvpx.so.5", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libopus.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/virtualbox/libopus.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

This is most likely a packaging error as virtualbox is attempting to load its bundled libraries.

**Comment by MingcongBai** [comment] 2019-01-29 20:39
@eatradish Did the commit above fix the issue?

**Comment by eatradish** [comment] 2019-01-30 08:31
> @eatradish Did the commit above fix the issue?

I thought it was fixed, but it didn't actually

**Comment by MingcongBai** [comment] 2019-02-01 07:47
Fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/5d40ff454c16d166d890c76332d1e3eef38ad34e. Closing.

**Closed as completed by MingcongBai** 2019-02-01 07:47 UTC
Labels: bug
