### ISSUE TITLE
krunner: run it from Konsole hits SIGSEGV (core dump)

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#479] opened 2016-10-22 11:44 UTC
Its GUI(maybe a fork) works at the same time perfectly but itself breaks.

```
lion@Lion-Laptop [ ~ ] $ krunner 
段错误 (核心已转储)
lion@Lion-Laptop [ ~ ] ! 
```

**Comment by LionNatsu** [comment] 2016-10-22 12:12
The first krunner runs as a daemon, and other krunner notify it to show a input box then exit. The question is why they don't exit (normally) but crash.

**Comment by MingcongBai** [comment] 2016-10-22 20:50
That's interesting...

**Comment by MingcongBai** [comment] 2016-10-22 20:50
```0x00007ffff6570dd7 in QObject::disconnect(QObject const*, char const*, QObject const*, char const*) ()
   from /usr/lib/libQt5Core.so.5```

**Comment by MingcongBai** [comment] 2016-10-23 02:56
Upstream bug reported at: https://bugs.kde.org/show_bug.cgi?id=371505.

**Comment by MingcongBai** [comment] 2016-10-23 04:04
This issue still exists with Plasma 5.8.2.

**Comment by liushuyu** [comment] 2016-10-26 04:33
I think more like a  bug of Qt, and need a debug build of Qt to figure it out, since Musescore has the exactly the same problem:
```
Thread 3 "QDBusConnection" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd657f700 (LWP 6944)]
0x00007ffff0d1a9cf in QObject::disconnect(QObject const*, char const*, QObject const*, char const*) () from /usr/lib/libQt5Core.so.5
(gdb) bt
#0  0x00007ffff0d1a9cf in QObject::disconnect(QObject const*, char const*, QObject const*, char const*) () at /usr/lib/libQt5Core.so.5
#1  0x00007fffe1e8e530 in  () at /usr/lib/libQt5DBus.so.5
#2  0x00007fffe1e7af62 in  () at /usr/lib/libQt5DBus.so.5
#3  0x00007ffff0b10d78 in  () at /usr/lib/libQt5Core.so.5
#4  0x00007ffff5e4d454 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007ffff020f7df in clone () at /usr/lib/libc.so.6
(gdb) _
```

**Comment by LionNatsu** [comment] 2016-10-27 14:35
@liushuyu What does it mean? Ummm... Tries to disconnect a closed connection? Or a null connection?

**Comment by MingcongBai** [comment] 2017-05-26 08:24
Is this issue still here? @LionNatsu

**Comment by liushuyu** [comment] 2017-10-17 00:02
Seems like this problem is resolved in later Qt 5 builds. Please confirm.

**Comment by MingcongBai** [comment] 2021-03-15 02:53
Probably resolved since it can no longer be reproduced (obviously...). Closing.

**Closed by MingcongBai** 2021-03-15 02:53 UTC
Labels: bug, in-progress
