### ISSUE TITLE
Firefox: bugs

### ISSUE THREAD

**Issue by bobcao3** [AOSC-Dev/aosc-os-abbs#16] opened 2015-07-15 17:46 UTC
When starting firefox, input w or press Ctrl+A causing core dump of firefox.
When resuming from suspend, it could be disappeared

**Comment by MingcongBai** [comment] 2015-07-23 08:55
Could be fixed with the latest `gtk-2` update, can you check on how it works now?

**Comment by bobcao3** [comment] 2015-08-03 02:56
It's still have problems, switching windows could cause it terminated now.

**Comment by MingcongBai** [comment] 2015-08-05 05:01
@Icenowy reports that this issue shows on his machine, too.

**Comment by MingcongBai** [comment] 2015-08-10 17:05
Cannot reproduce anyways. Closing. Please re-open if found again, attach with stack trace.

**Closed by MingcongBai** 2015-08-10 17:05 UTC
Labels: bug, help wanted
